# Generated by Django 6.0.4 on 2026-04-14 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QAHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
                ("sources", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                (
                    "author",
                    models.CharField(blank=True, default="Unknown", max_length=300),
                ),
                ("rating", models.FloatField(blank=True, null=True)),
                ("num_reviews", models.IntegerField(default=0)),
                ("description", models.TextField(blank=True, default="")),
                ("price", models.CharField(blank=True, default="", max_length=50)),
                ("book_url", models.URLField(blank=True, default="", max_length=1000)),
                (
                    "cover_image_url",
                    models.URLField(blank=True, default="", max_length=1000),
                ),
                ("genre", models.CharField(blank=True, default="", max_length=200)),
                (
                    "availability",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("upc", models.CharField(blank=True, default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_processed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["genre"], name="books_book_genre_4a7cdf_idx"),
                    models.Index(
                        fields=["rating"], name="books_book_rating_d06a65_idx"
                    ),
                    models.Index(fields=["title"], name="books_book_title_d3218d_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("summary", "Summary"),
                            ("genre_classification", "Genre Classification"),
                            ("sentiment", "Sentiment Analysis"),
                            ("recommendation_reason", "Recommendation Reason"),
                        ],
                        max_length=50,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to="books.book",
                    ),
                ),
            ],
            options={
                "ordering": ["insight_type"],
                "unique_together": {("book", "insight_type")},
            },
        ),
        migrations.CreateModel(
            name="BookChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_index", models.IntegerField()),
                ("content", models.TextField()),
                ("chroma_id", models.CharField(max_length=200, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="books.book",
                    ),
                ),
            ],
            options={
                "ordering": ["book", "chunk_index"],
                "unique_together": {("book", "chunk_index")},
            },
        ),
    ]
